name: Reduce README
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # local repository checkout required for the add-and-commit action
      - name: Checkout Local Repository
        uses: actions/checkout@v4
      - name: Checkout Remote Repository
        uses: actions/checkout@v4
        with:
          repository: robertmcnees/gs-scheduling-tasks
          ref: main
          path: './main'
      - name: Install Asciidoctor Reducer
        run: sudo gem install asciidoctor-reducer
      - name: Reduce README
        # to preserve preprocessor conditionals, add the --preserve-conditionals option
        run: asciidoctor-reducer -a env-build-for-spring-academy -a allow-uri-read -o README-reduced.adoc main/README.adoc
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Downdoc
        run: npx downdoc -o README-spring-academy.md README-reduced.adoc
      - name: Commit and Push README
        uses: EndBug/add-and-commit@v9
        with:
          add: README-spring-academy.md
